### ISSUE TITLE
Episode #260 - Missing template error

### ISSUE THREAD

**Issue by ests** [ryanb/railscasts-episodes#11]
I am trying to run chatter-after just as I cloned it from repo, faye running on thin just as described. Unfortunately, after visiting http://localhost:3000/ and hitting "Send" button, HTTP 500 is returned from rails (and 200 from faye):

```
Template is missing
Missing template messages/create with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml], :formats=>[:html], :locale=>[:en, :en]} in view paths "/home/ernest/programming/sandbox/ruby/episode-260/chatter-after/app/views"
```

**Comment by rderoldan1** [comment]
@ests I've fixed 260 episode, look at the episodi at my repository, only you have to update the app to rails 3.1
https://github.com/rderoldan1/railscasts-episodes/tree/to-rails-3.1/episode-260

**Comment by binyamindavid** [comment]
@rderoldan1 your solution doesn't seem to work.

**Comment by rderoldan1** [comment]
@vezu tell me  the error please
