### ISSUE TITLE
config/routes.rb:83:in `block in <top (required)>': uninitialized constant Subdomain (NameError)

### ISSUE THREAD

**Issue by Unitech** [ryanb/railscasts-episodes#12]
Rails 3.1rc6

Problem solved by adding :

config.autoload_paths += Dir["#{config.root}/lib/**/"]

in config/application.rb

**Comment by ekumachidi** [comment]
Adding

```
require 'subdomain'
```

before the routes block fixes this

Another alternative is to use lambda expression in your route so you have the logic in the routes constraint, like this
        constraints: lambda {|request| request.subdomain.present? && request.subdomain != "www" }
