### ISSUE TITLE
Episode 260 Messages

### ISSUE THREAD

**Issue by yaboyanees** [ryanb/railscasts-episodes#5]
Can not install Faye.. I tried numerous ways and i get an error saying failed to install gem because of a make_out file conflict. Any guidance or suggestions?

**Comment by ryanb** [comment]
I'm not sure, I suggest asking on the mailing list. http://groups.google.com/group/faye-users

**Comment by yaboyanees** [comment]
Thanks for replying. Here is a screen shot if you could please take a look..I am a huge fan of your work btw.

[cid:image001.png@01CBF8EE.C039CEF0]

V/R

-Anees Merzi

**Comment by ryanb** [comment]
The screenshot isn't showing up. Maybe just link to it?

**Comment by yaboyanees** [comment]
Here is the 2nd attempt to show the screen shot. Hopefully it works!

C:\Users\x13598\Pictures\screenshot.jpgfile:///C:Usersx13598Picturesscreenshot.jpg

**Comment by yaboyanees** [comment]
I asked a buddy to try to install faye and he got the same exact error.?
We are both using rails 3.0.3 and ruby sdk 1.8.7

**Comment by ryanb** [comment]
The image still isn't showing up. I am guessing this is Windows specific. I don't have access to a Windows machine so I don't think I will be much help. I suggest asking on the Faye mailing list to make sure Windows is a supported platform for it.
